<template>
  <Teleport to="body">
    <Modal v-model="fieldModal" @update:model-value="handleClose">
      <div
        class="flex-col xl:w-[30%] lg:w-[40%] md:w-[60%] w-[90%] rounded-lg shadow-xl"
      >
        <!-- Modal Header -->
        <div
          class="flex items-center justify-between py-2 px-4 bg-indigo-600 text-white rounded-t-lg sticky top-0 z-10 shadow-sm"
        >
          <!-- Close Button -->
          <i
            class="fa-solid fa-arrow-left-long cursor-pointer bg-white p-2 text-[20px] rounded-full text-indigo-600 hover:bg-indigo-900 hover:text-white duration-200 h-[36px] aspect-1 flex justify-center items-center"
            @click="handleClose"
          ></i>
          <!-- Confirm Button -->
          <i
            class="fa-solid fa-check cursor-pointer text-[20px] bg-white p-2 rounded-full text-teal-600 hover:bg-teal-900 hover:text-white duration-200 h-[36px] aspect-1 flex justify-center items-center"
            @click="handleConfirm"
            v-if="isEnabled"
          ></i>
        </div>

        <!-- Modal Content -->
        <div
          class="bg-gray-50 p-6 rounded-b-lg space-y-4"
          :class="{
            'flex items-center space-x-4': schema[field] === 'boolean',
            'space-y-4': schema[field] !== 'boolean',
          }"
        >
          <!-- Field Label -->
          <div class="text-gray-700 font-semibold">
            {{ route.params.field }}:
          </div>

          <!-- Input Field -->
          <div :class="{ 'w-full': schema[field] !== 'boolean' }">
            <!-- Boolean Field (Toggle) -->
            <div v-if="schema[field] === 'boolean'">
              <Toggle v-model="fieldData" :disabled="schema[field].disabled" />
            </div>

            <!-- Password Fields -->
            <div
              v-else-if="route.params.field === 'password'"
              class="space-y-4"
            >
              <div class="space-y-2">
                <input
                  class="input w-full border border-gray-300 rounded-lg p-2 focus:outline-none focus:ring-2 focus:ring-indigo-500"
                  type="password"
                  :class="{ 'input-error': changePasswordError.password }"
                  v-model="changePasswordInfo.password"
                  placeholder="Nhập mật khẩu..."
                />
                <div
                  class="text-sm text-red-600"
                  v-if="changePasswordError.password"
                >
                  {{ changePasswordError.password }}
                </div>
              </div>
              <div class="space-y-2">
                <input
                  class="input w-full border border-gray-300 rounded-lg p-2 focus:outline-none focus:ring-2 focus:ring-indigo-500"
                  type="password"
                  :class="{
                    'input-error': changePasswordError.passwordConfirm,
                  }"
                  v-model="changePasswordInfo.passwordConfirm"
                  placeholder="Nhập lại mật khẩu"
                />
                <div
                  class="text-sm text-red-600"
                  v-if="changePasswordError.passwordConfirm"
                >
                  {{ changePasswordError.passwordConfirm }}
                </div>
              </div>
            </div>

            <!-- Text Input Field -->
            <div v-else>
              <input
                class="input w-full border border-gray-300 rounded-lg p-2 focus:outline-none focus:ring-2 focus:ring-indigo-500"
                type="text"
                v-model="fieldData"
                :disabled="
                  schema[field].disabled ||
                  schema[field].autoGenerated ||
                  schema[field].relation
                "
              />
            </div>
          </div>
        </div>
      </div>
    </Modal>
  </Teleport>
</template>
<script setup lang="ts">
import { useToast } from "vue-toastification";

const route = useRoute();
const router = useRouter();
const fieldModal = ref(false);
const { user } = useAuth();
const schemaApi = "/schema/user";
const schema = useState<any>(schemaApi);
const field = route.params.field as string;
const fieldData = ref<any>(user.value[field as keyof TUser] || "null");
const { isFromInside } = useGetState();
const { loading } = useGetState();
const toast = useToast();
const { getUser } = useAuth();

setTimeout(() => {
  fieldModal.value = true;
}, 50);

const isEnabled = computed(() => {
  if (
    field === "username" &&
    (!user.value.isEditedUsername || user.value.rootUser)
  ) {
    return true;
  }

  if (
    field !== "username" &&
    !schema.value[field].disabled &&
    !schema.value[field].autoGenerated &&
    !schema.value[field].relation
  ) {
    return true;
  }
  return false;
});

const changePasswordInfo = ref<{
  [key: string]: string;
}>({
  password: "",
  passwordConfirm: "",
});

const changePasswordError = ref<{
  [key: string]: string;
}>({
  password: "",
  passwordConfirm: "",
});

async function handleClose() {
  if (isFromInside.value) {
    router.back();
  } else {
    await navigateTo(
      {
        name: "me",
      },
      { replace: true }
    );
  }
}

const isChangePasswordValid = computed(() => {
  let result = true;
  for (const [key, value] of Object.entries(changePasswordInfo.value)) {
    if (!value) {
      result = false;
      changePasswordError.value[key] = "Không được để trống!";
    } else {
      result = true;
      changePasswordError.value[key] = "";
    }
  }

  if (
    changePasswordInfo.value.password !==
    changePasswordInfo.value.passwordConfirm
  ) {
    result = false;
    changePasswordError.value.passwordConfirm = "Password chưa khớp!";
  }

  for (const [key, value] of Object.entries(changePasswordError.value)) {
    if (value) {
      result = false;
    }
  }
  return result;
});

async function handleConfirm() {
  if (route.params.field === "password") {
    if (!isChangePasswordValid.value) return;
  }
  loading.value = true;
  await useApi("/me", {
    method: "PATCH",
    body: {
      [route.params.field as string]:
        route.params.field === "password"
          ? changePasswordInfo.value.password
          : fieldData.value,
    },
  });
  await getUser();
  await handleClose();
  toast.success("Thành công");
  loading.value = false;
}

watch(
  () => [
    changePasswordInfo.value.password,
    changePasswordInfo.value.passwordConfirm,
  ],
  ([newPassword, newPasswordConfirm], [oldPassword, oldPasswordConfirm]) => {
    if (newPassword !== oldPassword) {
      if (newPasswordConfirm) {
        if (newPasswordConfirm !== newPassword)
          changePasswordError.value.passwordConfirm = "Password không khớp!";
        else changePasswordError.value.passwordConfirm = "";
      } else changePasswordError.value.password = "";
      if (!newPassword)
        changePasswordError.value.password = "Không được để trống";
      else changePasswordError.value.password = "";
    } else if (newPasswordConfirm !== oldPasswordConfirm) {
      if (newPasswordConfirm !== newPassword && newPassword) {
        changePasswordError.value.passwordConfirm = "Password không khớp!";
      } else if (!newPasswordConfirm)
        changePasswordError.value.passwordConfirm = "Không được để trống!";
      else changePasswordError.value.passwordConfirm = "";
    } else
      changePasswordError.value = {
        password: "",
        passwordConfirm: "",
      };
  }
);

async function getSchema() {
  if (schema.value) return;
  const result: any = await useApi(schemaApi);
  schema.value = result.data;
}
await getSchema();

definePageMeta({
  middleware: [
    async (to, from) => {
      const { isFromInside } = useGetState();
      if (from.name) isFromInside.value = true;
      const schemaApi = "/schema/user";
      const schema = useState<any>(schemaApi, () => {});

      async function getSchema() {
        if (schema.value) return;
        const result: any = await useApi(schemaApi);
        schema.value = result.data;
      }
      await getSchema();
    },
  ],
});
</script>
