<template>
  <div
    class="h-fit flex flex-col max-h-full xl:w-2/3 w-full mx-auto md:p-4 p-1 bg-gray-50 rounded-lg shadow-lg"
  >
    <div
      class="max-h-[85%] overflow-y-scroll hidden-scrollbar space-y-2 rounded-lg bg-white"
    >
      <!-- Header -->
      <div
        class="p-4 bg-gradient-to-r from-indigo-600 to-purple-600 text-white font-semibold md:text-lg text-md flex items-center justify-between rounded-lg sticky top-0 shadow-md"
      >
        <span>Thông tin cá nhân</span>
      </div>

      <!-- Information list -->
      <template v-for="(key, index) in Object.keys(schema)" :key="index">
        <NuxtLink
          v-if="key !== 'rootUser'"
          :to="
            isEnabled(key)
              ? {
                  name: 'me-field',
                  params: { field: key },
                }
              : undefined
          "
          class="flex items-center justify-between odd:bg-gray-100 even:bg-gray-200 md:p-4 p-3 rounded-lg hover:bg-indigo-100 transition-colors"
        >
          <div class="text-gray-900 font-medium capitalize">{{ key }}</div>
          <div
            class="text-indigo-900 font-semibold xl:max-w-[250px] md:max-w-[200px] max-w-[140px] flex items-center space-x-2"
          >
            <div class="truncate">
              {{
                key === "password"
                  ? "********"
                  : user[key as keyof TUser]
                  ? user[key as keyof TUser]
                  : user[key as keyof TUser] === false
                  ? "false"
                  : "null"
              }}
            </div>
            <i class="fa-solid fa-chevron-right" v-if="isEnabled(key)"></i>
          </div>
        </NuxtLink>
      </template>
    </div>
  </div>
  <NuxtPage />
</template>

<script setup lang="ts">
const { user } = useAuth();
const schemaApi = "/schema/user";
const schema = useState<any>(schemaApi, () => {});
const { loading } = useGetState();

function isEnabled(key: string) {
  if (
    key === "username" &&
    (!user.value.isEditedUsername || user.value.rootUser)
  ) {
    return true;
  }

  if (
    key !== "username" &&
    !schema.value[key].disabled &&
    !schema.value[key].autoGenerated &&
    !schema.value[key].relation
  ) {
    return true;
  }
  return false;
}

async function getSchema() {
  if (schema.value) return;
  loading.value = true;
  const result: any = await useApi(schemaApi);
  schema.value = result;
  loading.value = false;
}

await getSchema();
</script>
